"""Adding email to user table 01

Revision ID: 024ba572eff6
Revises: 1c62cea2ccc8
Create Date: 2025-02-24 12:03:37.654755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024ba572eff6'
down_revision: Union[str, None] = '1c62cea2ccc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
