"""Adding email to user table

Revision ID: 1c62cea2ccc8
Revises: 7126f7d9ccbe
Create Date: 2025-02-24 12:01:38.733674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c62cea2ccc8'
down_revision: Union[str, None] = '7126f7d9ccbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
