"""Removing index to user table

Revision ID: 65a88df6bb72
Revises: b96d39f03570
Create Date: 2025-02-24 13:43:39.060769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a88df6bb72'
down_revision: Union[str, None] = 'b96d39f03570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_User_Name', table_name='User')
    op.drop_index('ix_User_Password', table_name='User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_User_Password', 'User', ['Password'], unique=False)
    op.create_index('ix_User_Name', 'User', ['Name'], unique=False)
    # ### end Alembic commands ###
