"""Remving Invoice Table

Revision ID: 6c3359e4906c
Revises: 981c31af0f66
Create Date: 2025-02-26 12:04:52.084951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3359e4906c'
down_revision: Union[str, None] = '981c31af0f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Invoice_Description', table_name='Invoice')
    op.drop_index('ix_Invoice_Id', table_name='Invoice')
    op.drop_index('ix_Invoice_Name', table_name='Invoice')
    op.drop_table('Invoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invoice',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK__Invoice__3214EC071EDBFCC6')
    )
    op.create_index('ix_Invoice_Name', 'Invoice', ['Name'], unique=False)
    op.create_index('ix_Invoice_Id', 'Invoice', ['Id'], unique=False)
    op.create_index('ix_Invoice_Description', 'Invoice', ['Description'], unique=False)
    # ### end Alembic commands ###
