"""Test column 02

Revision ID: 981c31af0f66
Revises: dc4d16b27aa6
Create Date: 2025-02-26 12:04:00.601246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981c31af0f66'
down_revision: Union[str, None] = 'dc4d16b27aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invoice',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Invoice_Description'), 'Invoice', ['Description'], unique=False)
    op.create_index(op.f('ix_Invoice_Id'), 'Invoice', ['Id'], unique=False)
    op.create_index(op.f('ix_Invoice_Name'), 'Invoice', ['Name'], unique=False)
    op.add_column('Product', sa.Column('Test', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_Product_Test'), 'Product', ['Test'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Product_Test'), table_name='Product')
    op.drop_column('Product', 'Test')
    op.drop_index(op.f('ix_Invoice_Name'), table_name='Invoice')
    op.drop_index(op.f('ix_Invoice_Id'), table_name='Invoice')
    op.drop_index(op.f('ix_Invoice_Description'), table_name='Invoice')
    op.drop_table('Invoice')
    # ### end Alembic commands ###
