"""Adding product table

Revision ID: a2329b0f5595
Revises: cfab6eb06a52
Create Date: 2025-02-24 12:17:14.555450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2329b0f5595'
down_revision: Union[str, None] = 'cfab6eb06a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Product_Description'), 'Product', ['Description'], unique=False)
    op.create_index(op.f('ix_Product_Id'), 'Product', ['Id'], unique=False)
    op.create_index(op.f('ix_Product_Name'), 'Product', ['Name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Product_Name'), table_name='Product')
    op.drop_index(op.f('ix_Product_Id'), table_name='Product')
    op.drop_index(op.f('ix_Product_Description'), table_name='Product')
    op.drop_table('Product')
    # ### end Alembic commands ###
